//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multiple_models_one_view.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cricketer_IPL_Statstics
    {
        public int IPL_Id { get; set; }
        public string Team_Name { get; set; }
        public Nullable<int> ID { get; set; }
    
        public virtual Cricketer Cricketer { get; set; }
    }
}
