//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multiple_models_one_view.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public int depid { get; set; }
        public string depname { get; set; }
        public Nullable<int> toilerid { get; set; }
    
        public virtual toiler toiler { get; set; }
    }
}
