//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multiple_models_one_view.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int login_id { get; set; }
        public string username { get; set; }
        public string userpwd { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public string Usertype { get; set; }
        public string Mobile { get; set; }
    }
}
