//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multiple_models_one_view.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_context : DbContext
    {
        public db_context() : base("name=db_context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Cricketer_Details> Cricketer_Details { get; set; }
        public virtual DbSet<Cricketer_IPL_Statstics> Cricketer_IPL_Statstics { get; set; }
        public virtual DbSet<Cricketer_ODI_Statistics> Cricketer_ODI_Statistics { get; set; }
        public virtual DbSet<Cricketer_Test_Statistics> Cricketer_Test_Statistics { get; set; }
        public virtual DbSet<Cricketer> Cricketers { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<toiler> toilers { get; set; }
    }
}
